name: Dependency Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run OWASP Dependency-Check
      run: echo "Implement OWASP Dependency-Check here"